
# Initialization
```{r}
rm(list=ls())
source("Utils.R")

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# MACD Strategy
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
macd_strategy = function(dat_i) {

  # techinicals
  ema50       = ema(dat_i$close, 50)
  ema200      = ema(dat_i$close, 200)
  macd12_26_9 = macd(dat_i$close, 12, 26, 9)
  
  # entry
  macd_cross  = crossover(macd12_26_9$signal,macd12_26_9$MACD)
  
  # entry signals
  macd_entry = which(macd_cross & macd12_26_9$MACD < 0 & dat_i$close > ema200)
  
  # loop through macd entries, how to find prior swing low, use that as stop loss, and take profit is 1.5x greater
  out_date_entry = as.Date(c())
  out_date_exit  = as.Date(c())
  out_return     = as.numeric(c())
  
  for (m in macd_entry) {
    
    # get local region of current price/date
    price     = dat_i$close[max(c((m - 100),1)):m]
    price_low = dat_i$low[max(c((m - 100),1)):m]
    date      = dat_i$date[max(c((m - 100),1)):m]
    
    # compute prior swing low
    price_smooth = smooth(c(price, price[length(price)]*seq(1.01,by=0.01,length=50)),0.1)[1:length(price)]
    minimas      = local_extrema(price_smooth,max=FALSE)
    min_ind      = minimas[length(minimas)]
    min_date     = date[min_ind]
    
    # find minimum in local region of min_date
    min_date = date[which.min(price_low[max(c(1,(min_ind - 5))):min(c(length(price_low),(min_ind + 5)))]) + min_ind - 6]
    
    # set prices
    price_entry = dat_i$close[m]
    price_stop  = dat_i$low[dat_i$date == min_date]*0.995 # put stop loss %0.5 below prior swing low
    price_profit= dat_i$close[m] * (1 + (price_entry - price_stop)/price_entry * 1.5) # 1R:1.5R
    
    # find which price is hit first
    ind_stop = which(dat_i$low[m:nrow(dat_i)] <= price_stop)[1] + m - 1
    ind_exit = which(dat_i$high[m:nrow(dat_i)] >= price_profit)[1] + m - 1
    
    outcome   = which.min(c(ind_stop,ind_exit))
    exit_date = min(c(ind_stop,ind_exit),na.rm=TRUE)
    
     # store the trade if there is an exit
    if (is.finite(exit_date)) {
      
      # set dates
      date_entry = dat_i$date[m] # enter at next candle
      date_stop  = min_date
      date_exit  = dat_i$date[exit_date]
      
      # compute profits/loss
      return = ifelse(outcome==1,-1,1.5)
  
      # save data
      out_date_entry = c(out_date_entry,date_entry)
      out_date_exit  = c(out_date_exit,date_exit)
      out_return = c(out_return, return)
      
    }
    
  }

  return(list(wins   = sum(out_return>0)/length(out_return)*100,
              n      = length(out_return),
              trade_return = out_return,
              trade_date   = out_date_exit))
  
}
```

# Load and Run MACD and EMA strategies
```{r}
# set up stocks
stocks = read.csv("NASDAQ.csv")
stocks = stocks[,c("Symbol", "Cap", "Float")]

stocks$macd_return = NA
stocks$macd_n      = NA

macd_trade=c();macd_date=as.Date(c())

# read stock data
for (i in 1:nrow(stocks)) {
  
    print(stocks$Symbol[i])
  
    # load stock
    path = file.path(Sys.getenv("USERPROFILE"),"Desktop","nasdaq stocks")
    df   = read.csv(paste0(path,"/",stocks$Symbol[i],".csv"),sep=",",header=TRUE,stringsAsFactors=FALSE)
    
    # run strategies
    macd_out = macd_strategy(df)
    
    # save winning percentages and number of trades
    stocks$macd_return[i] = macd_out$wins
    stocks$macd_n[i]      = macd_out$n
    macd_trade = c(macd_trade, macd_out$trade_return)
    macd_date  = c(macd_date, macd_out$trade_date)
  
}

# plot profit graphs
macd_trade = cumprod(1+macd_trade[order(macd_date)]/100)
macd_date  = sort(macd_date)

plot(as.Date(macd_date),macd_trade,type="l",log="y")

# summarize and write to output
sum(stocks$macd_return * stocks$macd_n / sum(stocks$macd_n,na.rm=TRUE),na.rm=TRUE)

write.csv(stocks,"macd_returns.csv",row.names=FALSE)
``` 

# Further Filtering Based on Results
```{r}
# load returns
returns = read.csv("macd_returns.csv",sep=",")

# compute additional metrics
# for (i in 1:nrow(returns)) {
#   
#   print(returns$Symbol[i])
#   
#   path = file.path(Sys.getenv("USERPROFILE"),"Desktop","nasdaq stocks")
#   
#   df = read.csv(paste0(path,"/",returns$Symbol[i],".csv"),sep=",",header=TRUE,stringsAsFactors=FALSE)
# 
# }

# filter
returns_subset = returns[!is.na(returns$Cap) & returns$macd_n != 0,]
returns_subset = returns_subset[returns_subset$Cap>10000,] # only take large caps

# compute summaries
s1 = sum(returns_subset$macd_n)/26
s2 = sum(returns_subset$macd_return * returns_subset$macd_n / sum(returns_subset$macd_n,na.rm=TRUE),na.rm=TRUE)

sprintf("Average Number of Trades Per Year: %0.f, with Winning Percentage: %0.1f%%",s1,s2)
```

- filter out stocks with negative slope after linear regression
- compute MSE from linear regression line, and compare metrics to return
- trailing stop loss
- add major support/resistance (dont enter below resistance, use strong support as better entry or stop)